version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
      - es-data:/usr/share/elasticsearch/data
    networks:
      - efk-setup-network

  kibana:
    image: kibana:7.10.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - efk-setup-network

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    networks:
      - efk-setup-network

  #app:
  #  image: back-gammon-app-00
  #  links:
  #    - "elasticsearch"
  #  ports:
  #    - "8080:8080"
  #  networks:
  #    - efk-setup-network

networks:
  efk-setup-network:
    driver: bridge

volumes:
  grafana-data:
  es-data: